### ISSUE TITLE
Error on test phase during building via maven 

### ISSUE THREAD

**Issue by Kosmachevskiy** [derjust/spring-data-dynamodb#101]
Version 5.0.0
 
I'm trying to run tests with new version but:
`java.lang.ClassNotFoundException: org.springframework.data.querydsl.QuerydslUtils`

When I use 4.5.0 and all the test are pass.

So I'm still using previous version.

**Comment by derjust** [comment]
`org.springframework.data.querydsl.QueryDslUtils` was renamed to `org.springframework.data.querydsl.QuerydslUtils` with spring-data 2.0.

Do you use additional dependencies that might altered the dependency list? 
What's your JDK version you built  0de29eb with?

**Comment by derjust** [comment]
Sadly not reproducible on my end :-(
