### ISSUE TITLE
Create table when not exist

### ISSUE THREAD

**Issue by derjust** [derjust/spring-data-dynamodb#17]
> Migration of https://github.com/michaellavelle/spring-data-dynamodb/issues/63

**Comment by maxsap** [comment]
+1

**Comment by fnouama** [comment]
+1

**Comment by kennyk65** [comment]
+1, like you can with hibernate.hbm2ddl.auto.  The metadata the @DynamoDBTable object could be digested and used to call com.amazonaws.services.dynamodbv2.document.DynamoDB.createTable().

**Comment by OllyJFox** [comment]
+1

**Comment by aashishmodak** [comment]
+1

**Comment by ranjeethpt** [comment]
+1

**Comment by alexandredavi** [comment]
+1

**Comment by khoubyari** [comment]
+1

**Comment by sarbajitdutta** [comment]
Can somebody please point me to an example for the implementation? I want to create tables if it does not exist in dynamodb when spring boot starts up.

**Comment by jfleck1** [comment]
Here's a code snippet to do it. 

```
private void initializeTables(AmazonDynamoDB amazonDynamoDB) {
        DynamoDBMapper dynamoDBMapper = new DynamoDBMapper(amazonDynamoDB);

        // Alternatively, you can scan your model package for the DynamoDBTable annotation
        List<Class> modelClasses = new ArrayList<>();
        modelClasses.add(Layer.class);
        modelClasses.add(Marker.class);

        for (Class cls : modelClasses) {
            LOGGER.info("Creating DynamoDB table for " + cls.getSimpleName());
            CreateTableRequest tableRequest = dynamoDBMapper.generateCreateTableRequest(cls);
            tableRequest.setProvisionedThroughput(new ProvisionedThroughput(1L, 1L));

            boolean created = TableUtils.createTableIfNotExists(amazonDynamoDB, tableRequest);

            if (created) {
                LOGGER.info("Created DynamoDB table for " + cls.getSimpleName());
            } else {
                LOGGER.info("Table already exists for " + cls.getSimpleName());
            }
        }

        ListTablesResult tablesResult = amazonDynamoDB.listTables();

        LOGGER.info("Current DynamoDB tables are: ");
        for (String name : tablesResult.getTableNames()) {
            LOGGER.info("\t" + name);
        }

    }
```

**Comment by enriquezrene** [comment]
+1

**Comment by v4ires** [comment]
> Here's a code snippet to do it.
> 
> ```java
> private void initializeTables(AmazonDynamoDB amazonDynamoDB) {
>         DynamoDBMapper dynamoDBMapper = new DynamoDBMapper(amazonDynamoDB);
> 
>         // Alternatively, you can scan your model package for the DynamoDBTable annotation
>         List<Class> modelClasses = new ArrayList<>();
>         modelClasses.add(Layer.class);
>         modelClasses.add(Marker.class);
> 
>         for (Class cls : modelClasses) {
>             LOGGER.info("Creating DynamoDB table for " + cls.getSimpleName());
>             CreateTableRequest tableRequest = dynamoDBMapper.generateCreateTableRequest(cls);
>             tableRequest.setProvisionedThroughput(new ProvisionedThroughput(1L, 1L));
> 
>             boolean created = TableUtils.createTableIfNotExists(amazonDynamoDB, tableRequest);
> 
>             if (created) {
>                 LOGGER.info("Created DynamoDB table for " + cls.getSimpleName());
>             } else {
>                 LOGGER.info("Table already exists for " + cls.getSimpleName());
>             }
>         }
> 
>         ListTablesResult tablesResult = amazonDynamoDB.listTables();
> 
>         LOGGER.info("Current DynamoDB tables are: ");
>         for (String name : tablesResult.getTableNames()) {
>             LOGGER.info("\t" + name);
>         }
> 
>     }
> ```

Hi @jfleck1 how to enable to scan automatically the annotated classes?

**Comment by derjust** [comment]
Feature will be available as part of `5.0.4`.
Documentation available in the [wiki](https://github.com/derjust/spring-data-dynamodb/wiki/Autocreate-Tables). 
Also the latest `-SNAPSHOT` build has the feature already added. Due to major reworks on the initialization code any beta-tests are highly welcome (Please open new issues)

**Comment by ahuruFoundation** [comment]
@derjust saw the wiki but not quite clear which option allows to create a table only when itnot exist.

**Comment by douglasnegrini** [comment]
Does anyone know if there's a way to setup the TTL config when the table is auto created through this mechanism? Can't seem to find it anywhere in the docs 🤔
