### ISSUE TITLE
Spring Event Emit is killing thread?

### ISSUE THREAD

**Issue by efenderbosch** [derjust/spring-data-dynamodb#170]
## Expected Behavior
findById returns an entity or null

## Actual Behavior
findById seems to kill the thread?

## Steps to Reproduce the Problem

  1. Create entity w/ compound (hash + range) ID
  1. Query by compound ID
  1. Debug, stepping through. 

## Specifications
  
  - Spring Data DynamoDB Version: 5.0.2 (2.0)
  - Spring Data Version: 2.0.7.RELEASE
  - AWS SDK Version: 1.11.344
  - Java Version: 1.8.0_162 - Java HotSpot(TM) 64-Bit Server VM 25.162-b12
  - Platform Details: Mac OS X 10.13.4

Compound ID is defined as in the example in the wiki. Full class is here: https://gist.github.com/efenderbosch/64c1446a4131035b69a164ebbb36422a

`SimpleDynamoDBCrudRepository::findById` calls `DynamoDBTemplate::load`, which then calls `DynamoDBTemplate::maybeEmitEvent`. That ends up calling `SimpleApplicationEventMulticaster::multicastEvent` which seems to just die. No logs, no exceptions, nothing. Any ideas on further information I can provide? Do I have something misconfigured? Is there a way to disable event emission at least temporarily?

**Comment by derjust** [comment]
I think some more information would be helpful:
* Are there/what kind of `ApplicationEventListener`s are registered?
* As your are stepping through it, in `DynamoDBTemplate::maybeEmitEvent`, is line `eventPublisher.publishEvent(event)` executed?
    * Is the `event` null?
* Does the queried entity exist?
    * Does the behavior differ between a query for an existing query vs. a query with a non-existing hash-range key?
* If no exception is shown, what do you actually encounter?

The used hash-range key looks quite normal/unsuspicious,

**Comment by efenderbosch** [comment]
It looks like it gets to ``AbstractApplicationEventMulticaster::retrieveApplicationListeners`` and just dies at ``synchronized (this.retrievalMutex)``

The queried entity exists.

I'll keep debugging. I don't have any custom ``ApplicationEventListener``s registered

**Comment by derjust** [comment]
Are you sure the thread dies or does it just get parked due to the `retrievalMutex`?

**Comment by efenderbosch** [comment]
Not really sure. The repo never returns a value, though. And I thought events were broadcast in a separate Executor. Using ``IDynamoDbMapper::load`` returns a value immediately. Sorry, I didn't have much time to dig in to this today. I'll pick it up again tomorrow.

**Comment by derjust** [comment]
Are you able to share a demo (unit test?) that showcases the issue?
I always lived under the impression that the events get dispatched and the method returns more or less immediately.
How does your `@Configuration` class look like?

**Comment by efenderbosch** [comment]
Configuration classes: https://gist.github.com/efenderbosch/eb1f2d762a9e795cd501780c8a5f8f5f

**Comment by efenderbosch** [comment]
Ok, I finally figured it out and feel kinda dumb.

So this application subscribes to DynamoDB streams via the KCL adapter. I started the worker in the main thread. That's what was blocking ``retrievalMutex``. I've now started it in a ``Executors.newSingleThreadExecutor()`` and it is working fine. Closing.
