### ISSUE TITLE
DynamoDBRepositoryFactory logs confusing warning if Spring Data Version.class.getPackage().getImplementationVersion() returns null

### ISSUE THREAD

**Issue by cvasilyev** [derjust/spring-data-dynamodb#171]
## 
  
  - Spring Data DynamoDB Version: `4.5.5`
  - Spring Data Version: `1.13.11.RELEASE`
  - AWS SDK Version: `1.11.289`
  - Java Version: `1.8.x`
  - Platform Details: `Mac OS, 10.13.4 (High Sierra)`

During the application startup, a confusing warning is logged (see the last line logged at the WARN level):

     018-06-12 16:02:39 INFO  o.s.s.d.d.r.s.DynamoDBRepositoryFactory --- Spring Data DynamoDB Version: 4.5.5 (2.0)
     2018-06-12 16:02:39 INFO  o.s.s.d.d.r.s.DynamoDBRepositoryFactory --- Spring Data Version:          null
     2018-06-12 16:02:39 INFO  o.s.s.d.d.r.s.DynamoDBRepositoryFactory --- AWS SDK Version:              1.11.289
     2018-06-12 16:02:39 INFO  o.s.s.d.d.r.s.DynamoDBRepositoryFactory --- Java Version:                 1.8.0_144 - Java HotSpot(TM) 64-Bit Server VM 25.144-b01
     2018-06-12 16:02:39 INFO  o.s.s.d.d.r.s.DynamoDBRepositoryFactory --- Platform Details:             Mac OS X 10.13.4
     2018-06-12 16:24:10 WARN  o.s.s.d.d.r.s.DynamoDBRepositoryFactory --- This Spring Data DynamoDB implementation might not be compatible with the available Spring Data classes on the classpath! NoDefClassFoundExceptions or similar might occur!

This is caused by the fact that the result of the following operation in `DynamoDBRepositoryFactory.java` (line 48) is `null` - although the legitimate version of Spring Data is used, apparently:

      		String springDataVersion = Version.class.getPackage().getImplementationVersion();

Not sure why the value is not set, and whether it is the same for all Spring Data versions, but the warning, while benign, may be scary...

**Comment by derjust** [comment]
Actually the version is only reported from Spring-Data 2.0 going forward.
Little we can do here to change that.

But as a matter of fact, this was version check was not meant to be backported to the `4.5.x` line to be honest.

**Comment by derjust** [comment]
Fixed in `4.5.6` that was just pushed to Maven Central

**Comment by mibollma** [comment]
Any Idea why I receive this warning with the combination below?

```
o.s.s.d.d.r.s.DynamoDBRepositoryFactory  : Spring Data DynamoDB Version: 5.0.4 (2.0)
o.s.s.d.d.r.s.DynamoDBRepositoryFactory  : Spring Data Version:          2.1.3.RELEASE
o.s.s.d.d.r.s.DynamoDBRepositoryFactory  : AWS SDK Version:              1.11.473
o.s.s.d.d.r.s.DynamoDBRepositoryFactory  : Java Version:                 1.8.0_191 - Java HotSpot(TM) 64-Bit Server VM 25.191-b12
o.s.s.d.d.r.s.DynamoDBRepositoryFactory  : Platform Details:             Windows 10 10.0
o.s.s.d.d.r.s.DynamoDBRepositoryFactory  : This Spring Data DynamoDB implementation might not be compatible with the available Spring Data classes on the classpath!
NoDefClassFoundExceptions or similar might occur!
```

**Comment by Aariv** [comment]
This may be due to version problem in the class path. Did you try changing the version?
