### ISSUE TITLE
Example project spring-data-dynamodb with spring-data-rest 

### ISSUE THREAD

**Issue by adriafp** [derjust/spring-data-dynamodb#173]
The example project referenced on the readme file about spring-data-dynamodb with spring-data-rest is incorrect, the right one is https://github.com/sparknetworks/DynamoDBExample.

Greetings,

**Comment by derjust** [comment]
In which regard do you consider it 'incorrect'?

**Comment by adriafp** [comment]
First of all I apologize for my English, may we "incorrect" is too strong. But on the readme file points out that https://github.com/derjust/spring-data-dynamodb-examples there's an example of spring-data-rest with spring-data-dynamodb and there isn't.

**Comment by derjust** [comment]
Just added as the fix for #15 just went in :)
