### ISSUE TITLE
Pass in table name via context or environment variable

### ISSUE THREAD

**Issue by derjust** [derjust/spring-data-dynamodb#18]
> Migration of https://github.com/michaellavelle/spring-data-dynamodb/issues/65

**Comment by derjust** [comment]
Check out https://github.com/derjust/spring-data-dynamodb/wiki/Alter-table-name-during-runtime

**Comment by umanohar** [comment]
This works great to alter table names during runtime. Is there a way to change the index names the same way?

**Comment by umanohar** [comment]
Specifically global index names
