### ISSUE TITLE
Pagination and filtering does not work together

### ISSUE THREAD

**Issue by symphonydarlys** [derjust/spring-data-dynamodb#180]
## Steps to Reproduce the Problem

  1.  Define a Dynamo Table for instance `Person` with `id`, `name`, `age` as attributes. 
  2. Define a repository inheriting of `PagingAndSortingRepository<Person, Integer>`
  3. Add the method:
    `public Page<Person> findAllByName(String name, Pageable pageable);`
  4 This method does not work.

## Specifications
  
  - Spring Data DynamoDB Version: 5.0.1
  - Spring Data Version: NA
  - AWS SDK Version: 1.11.119
  - Java Version: 1.8
  - Platform Details: NA

**Comment by derjust** [comment]
Hi @symphonydarlys 
I prepared some distinct test cases for the scenario you submitted [here](https://github.com/derjust/spring-data-dynamodb/pull/181/commits/711245286f9a06cb60f5d0d22854a5330b86dc92#diff-578053794b5b03bd5e26c96371b3af2c).

Can you spot what's different to your scenario?

**Comment by symphonydarlys** [comment]
Thanks a lot for your response. I did not identify any important different between my implementation and your example. Below you can see what I develop to have this issue:

**My document:**
@DynamoDBTable(tableName = TABLE_NAME)
@Getter @Setter
public class TenantInfo {

  public static final String TABLE_NAME = "tp-tenant-dev";
  public static final String HASH_KEY_NAME = "tenant_id";

  @DynamoDBHashKey(attributeName = HASH_KEY_NAME)
  private String tenantId;
  @DynamoDBAttribute(attributeName = "fullname")
  private String fullName;
  @DynamoDBAttribute(attributeName = "shortname")
  private String shortName;
}

**The repository:**
public interface TenantInfoRepository extends PagingAndSortingRepository<TenantInfo, String> {

  /**
   * This method allows to get a tenant information using their identifier.
   * @param tenantId tenant identifier
   * @return a {@link TenantInfo}
   */
  Optional<TenantInfo> findById(String tenantId);

  /**
   * This method is to get all tenant information from DynanoDB. This method was added to validate that the
   * pod-discovery-service can get tenant information. We should remove this method in the future because we should use
   * methods applying pagination.
   * @return
   */
  @EnableScan
  Iterable<TenantInfo> findAll();

  /**
   * This method allows to get tenant information with pagination. Please see {@link Pageable}.
   * @param pageable this is an object implementing pageable to filter the result of the tenant research.
   * @return a List of {@link TenantInfo}.
   */
  @EnableScan
  @EnableScanCount
  public Page<TenantInfo> findAll(Pageable pageable);

  @EnableScan
  @EnableScanCount
  public Page<TenantInfo> findAllByFullName(String fullName, Pageable pageable);

  /**
   * This method returns the number of tenants in the database. It is currently used to check the connection to the database
   * in the service health indicator.
   */
  @EnableScan
  long count();
}

The method findAll(pageable) works well but when I invoked "repository.findAllByFullName("fullName", pageable)" I get this error:
TenantInfo[fullName]; no mapping for attribute by name.

**Comment by derjust** [comment]
Appreciate the update & glad you found it!
