### ISSUE TITLE
Readme example is not working

### ISSUE THREAD

**Issue by enriquezrene** [derjust/spring-data-dynamodb#199]
## Expected Behavior
No errors should happen after following the instructions in the README file

## Actual Behavior
There are even compilation problems and not all the tests are passing

## Steps to Reproduce the Problem

  1. Create a new spring-boot project
  2. Copy/paste the code
  3. Run the tests

## Specifications
  
- Compilation problems are happening
- Not all the tests are passing
- The table can not be deleted/created all the time

**Comment by derjust** [comment]
Updated the example project & updated `README.md`
Thanks for reporting!
