### ISSUE TITLE
Support for dynamodb-transactions

### ISSUE THREAD

**Issue by rmaugusto** [derjust/spring-data-dynamodb#202]
I think this library could add support for transactions with https://github.com/awslabs/dynamodb-transactions and Spring Transactions.

I could help with it. :-)

**Comment by derjust** [comment]
The main thread for this is #29 - And i started some poking a while ago in this [branch](https://github.com/derjust/spring-data-dynamodb/tree/Transactional)
Always open for PRs :)
(But as far as I can tell the referenced Github project is not the most active one)

**Comment by boostchicken** [comment]
https://aws.amazon.com/blogs/aws/new-amazon-dynamodb-transactions/
