### ISSUE TITLE
Gradle package

### ISSUE THREAD

**Issue by derjust** [derjust/spring-data-dynamodb#21]
> Migration of https://github.com/michaellavelle/spring-data-dynamodb/issues/70

**Comment by fpoolev** [comment]
This library can be included in a gradle project by adding the following to the root build.gradle file. As of this writing there are releases hosted on Maven Central for versions 4.3.1, 4.3.0, 4.2.3, 4.2.0, and 1.0.5. The README.md could be updated to describe how to add the project as a gradle dependency.

repositories {
    mavenCentral()
}

dependencies {
    compile group: 'com.github.derjust',
    name: 'spring-data-dynamodb',
    version: '4.2.3'
}

**Comment by derjust** [comment]
Thanks for the details.
`README.md` got an update
