### ISSUE TITLE
Add support for https://aws.amazon.com/blogs/aws/new-amazon-dynamodb-transactions/

### ISSUE THREAD

**Issue by boostchicken** [derjust/spring-data-dynamodb#224]
DynamoDB transactions are here!  Might do it myself, we'll see

**Comment by derjust** [comment]
Def. would love to add this to solve  #29 
(Closing as duplicate)

**Comment by boostchicken** [comment]
@derjust It's interesting, it allows you to tranact saves of multiple objects in a single dynamo call, which kind of flys in the face of how spring data does things. We are probably going to have a make a new type of repo that is "crud" for this since it could take pretty much any object.

Either that or use the @Transactional annotations and do some translation on the backend to wrap all the calls together some how.  Any thoughts?
