### ISSUE TITLE
DynamoDBIdIsHashAndRangeKeyEntityInformationImpl throws an exception when using both hash and range key definitions

### ISSUE THREAD

**Issue by emiliano-sala** [derjust/spring-data-dynamodb#25]
When using both ```@DynamoDBHashKey``` and ```@DynamoDBRangeKey``` the extractor ```org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBIdIsHashAndRangeKeyEntityInformationImpl``` throws an exception because:

1 - No ```@Id``` field is declared (```org.springframework.data.repository.core.support.ReflectionEntityInformation``` base class forces a explicit declaration of an annotated id)

2 - When ```@Id``` is used (for example in the hash key), it tries to look for fields annotated with ```@DynamoDBHashKey``` and/or ```@DynamoDBRangeKey``` within the id type (usually a String).

Using a separate type for the composite key also fails, since it class mapping still requires the hash key annotation.

**Comment by derjust** [comment]
Can you please post the source code and the resulting stacktrace?

**Comment by emiliano-sala** [comment]
Yeah, I can see from the example you posted how it actually works. I also saw a couple of extra examples in the https://github.com/michaellavelle/spring-data-dynamodb-demo project. 
It feels a little bit unnatural to define the hash and range keys twice (once in the id and the other in the mapping).
Having said that, i don't think this is an issue so I'm closing it. I appreciate you took the time to find some examples.

**Comment by derjust** [comment]
what exactly you define as "mapping"? The documentation needs for sure some improvement (#11) but at least to give some background:

You are using as primary key a RANGE+HASH. You need to do the following
* In your entity have a field annotated with `@Id` referencing a custom "key" class
* This key class itself has only the hash and range member fields - annotated with `@DynamoDBRangeKey` and `@DynamoDBHashKey` respectively.
- This also means that the generic for your `Repository` have to be updated to the new "key" class.

The background for this mumbojumbo is that spring-data requires to have a dedicated entity representing the key. As the `Repository.find()` method takes exactly one argument - `T` from your specific derived repository. Therefore the two fields, which constitute the "logical unique key", have to be wrapped in a single entity - the "key class" depicted above.

**Comment by emiliano-sala** [comment]
Yup, i went through the spring-data code and saw that same thing. I also confirmed the same on my code.
