### ISSUE TITLE
support for @AccessType(FIELD)

### ISSUE THREAD

**Issue by gurpiarbassi** [derjust/spring-data-dynamodb#268]
## Expected Behavior
I would like to remove setter methods and replace them with 
`@AccessType(AccessType.Type.FIELD)` at class level

## Actual Behavior
DynamoDBMappingException thrown by `com.amazonaws.services.dynamodbv2.datamodeling.StandardBeanProperties$MethodReflect.set(StandardBeanProperties.java:136)`

Looks like it's still looking for setters.

## Specifications
  
- Spring Data DynamoDB Version: 5.1.0 (2.1)
 - Spring Data Version:          2.1.10.RELEASE
- AWS SDK Version:              1.11.415
- Java Version:                 1.8.0_192 - OpenJDK 64-Bit Server VM 25.192-b01
- Platform Details:             Mac OS X 10.15

**Comment by boostchicken** [comment]
This is a problem with the AWS library

**Comment by gurpiarbassi** [comment]
Thanks @boostchicken I should have read the exception carefully 😃 
Closing issue.
