### ISSUE TITLE
no mechanism for supplying dynamically generated table names to certain types of queries 

### ISSUE THREAD

**Issue by cleroy** [derjust/spring-data-dynamodb#30]
I'm using CloudFormation to make my tables, and in general stuff is working great. I'm using a TableNameResolver which covers mapping table names for most access. Unfortunately, for access that uses certain queries -- basically anything going through the QueryRequest path of DynamoDBTemplate -- I have no workable way to provide table name overrides. These code paths call DynamoDBTemplate getOverriddenTableName, but that method doesn't consider my resolver, and I don't believe mapper config table name override stuff is sufficiently powerful to work with multiple CloudFormation tables.

I've got a pull request for a fix which is small -- I added an else if case to getOverriddenTableName that considers any TableNameResolver registered with the mapper config.

**Comment by cleroy** [comment]
Here's the pull request: https://github.com/derjust/spring-data-dynamodb/pull/31

**Comment by derjust** [comment]
Thanks for the pull request. 
Merged it and released a new version (`4.2.4` - it will become available in Maven Central in the next hours)
