### ISSUE TITLE
DynamoDBMarshalling field annotation is ignored in DynamoDBEntityMetadataSupport

### ISSUE THREAD

**Issue by ujann** [derjust/spring-data-dynamodb#32]
We used  `@DynamoDBMarshalling` as a field annotation in our model class to marshal a java enum.
Saving and loading works, but when we use this field within a criteria we get an exception in `AbstractDynamoDBQueryCriteria` stating `Cannot create condition for type:class xxx.domain.Status property conditions must be String,Number or Boolean, or have a DynamoDBMarshaller configured`.

In class `DynamoDBEntityMetadataSupport` method `public DynamoDBMarshaller<?> getMarshallerForProperty(final String propertyName)` the logic only checks for an annotation on the getter, so the `@DynamoDBMarshalling` field annotation is ignored.

**Comment by derjust** [comment]
Closed by PR #43
