### ISSUE TITLE
Dynamically change value of DynamoDBTable

### ISSUE THREAD

**Issue by maksimu** [derjust/spring-data-dynamodb#33]
I have three different environments (dev, stage, and prod) and for each environment I would like to change the value of the `tableName` in `@DynamoDBTable`.

In other words based on my profile the following need to be changed `@DynamoDBTable(tableName="dynamic-value")`

What would be the best approach to tackle this situation?

**Comment by maksimu** [comment]
The only clean way I see to implement it is to add additional column called `environment` and define there to which environment this particular record belong.

**Comment by derjust** [comment]
Does this help?
https://github.com/derjust/spring-data-dynamodb/wiki/Alter-table-name-during-runtime
Let us know if the documentation lacks precise information

**Comment by mburns-acom** [comment]
I tried this but ran into 2 problems.
First, builder.setTableNameResolver(tableNameOverrider) takes a Resolver not an Overrider.
Assuming you meant to call builder.setTableNameOverride(tableNameOverrider) I made the change and tested. But the prefix is not being added so my table is not being found. I get "Requested resource not found".

**Comment by mburns-acom** [comment]
Ok. I found my problem. I had used @EnableDynamoDBRepositories in 2 places and had not used it properly in one of them. Now it is working.

**Comment by derjust** [comment]
Cool. Thanks for reporting back!
