### ISSUE TITLE
Trouble trying to query dynamo by GSI

### ISSUE THREAD

**Issue by mswolfe** [derjust/spring-data-dynamodb#39]
I've read that there is support for querying by GSI but I just can't get it to work.  I'd really appreciate any help to point out exactly what I'm doing wrong.

I have a dynamo table with:
 - string customerId (Hash Key)
 - string createDt (Range Key)
 - string tag
I created a GSI called "tag" whose partition key is the string tag attribute.

I then created a method in my repository interface to query on the tag attribute:

    public interface CustomerHistoryRepository extends PagingAndSortingRepository<CustomerHistory, String> {
        CustomerHistory findByTag(string tag);
    }

Here is what the CustomerHistory object looks like with a composite key:
    
    @DynamoDBTable(tableName = "customerhistory")
    public class CustomerHistory implements Serializable{
        @Id
        private CustomerHistoryId id;
        
        @DynamoDBIndexHashKey
        private String tag;
    
        @DynamoDBHashKey(attributeName = "customerId")
        public String getId(){
            return id != null ? id.getCustomerId() : null;
        }
    
        public void setId(String customerId) {
            if(this.id == null) {
                this.id = new CustomerOfferHistoryId();
            }
            this.id.setCustomerId(customerId);
        }
    
        @Override
        @DynamoDBRangeKey(attributeName = "createDt")
        public String getCreateDt() {
            return id != null ? id.getCreateDt() : null;
        }
    
        @Override
        public void setCreateDt(String createDt) {
            if(this.id == null) {
                this.id = new CustomerOfferHistoryId();
            }

            this.id.setCreateDt(createDt);
        }
    }

And here is the composite key CustomerHistoryId
    
    @DynamoDBDocument
    public class CustomerHistoryId implements Serializable{
    
        @DynamoDBHashKey(attributeName = "customerId")
        private String customerId;
    
        @DynamoDBRangeKey(attributeName = "createDt")
        private String createDt;
    }

I left @EnableScan off of my repository to ensure it is not allowed to perform a scan and it throws an exception:
    org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalArgumentException: Scanning for this query is not enabled.  To enable annotate your repository method with @EnableScan, or enable scanning for all repository methods by annotating your repository interface with @EnableScan

Hopefully i'm just missing something simple!  Thanks again for any help at all.

**Comment by derjust** [comment]
Please have a look at this wiki article: https://github.com/derjust/spring-data-dynamodb/wiki/Use-Hash-Range-keys
And I added an unit test based on your data: 04fde30

There are some pieces that are not properly aligned in your example above. (It is a bit annoying to define some parts twice. Please read the wiki article for an explanation)

**Comment by mswolfe** [comment]
Thank you so much for the help!

I've now gotten it to issue the query correctly as expected.  Here's what I had to change to get it working in case someone else needs does the same silly things:
* I changed CustomerHistoryRepository to extend PagingAndSortingRepository<CustomerHistory, **CustomerHistoryId**> where it was specifying a String instead of the composite key.
* I removed the attributeName from the DynamoDBHashKey and DynamoDBRangeKey annotations in the CustomerHistoryId class.
* I am using lombok to generate the getter/setter for the tag property in the CustomerHistory class and I had to specify the index name on the @DynamoDBIndexHashKey annotation like so:

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "tag")

With everything setup correctly i was able to query the table through the tag index.

Sadly, I am still having an issue.

I have configured a custom TableNameResolver because the table names that I use in the @DynamoDBTable annotation do not match the actual names that my tables are created with.  The custom TableNameResolver is being respected on the save/load/delete methods, but it is ignored during the query.  Specifically the buildFinderQuery method in the DynamoDBEntityWithHashAndRangeKeyCriteria class here;https://github.com/derjust/spring-data-dynamodb/blob/master/src/main/java/org/socialsignin/spring/data/dynamodb/repository/query/DynamoDBEntityWithHashAndRangeKeyCriteria.java#L203.  Is this an unsupported feature?

Thanks again for the prompt help!

**Comment by mswolfe** [comment]
Just to follow up on my last issue.  I was using an old version of the library (v4.2.0) which did not have support for custom TableNameResolvers.  I have since updated to version 4.3.1 (latest) and the issue has gone away.

Again, thank you for all of the help.

**Comment by derjust** [comment]
Thanks for the feedback.
