### ISSUE TITLE
deleteBy...And... is not deleting records in Dynamo

### ISSUE THREAD

**Issue by Dmitry-Erokhin** [derjust/spring-data-dynamodb#46]
`repo.deletByKeyAndOtherKey(key, otherKey)` throws `EmptyResultDataAccessException` when no matching records exists, but works without exception if there is one match. 

**In both cases no records actually deleted from database**

**Comment by derjust** [comment]
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_DeleteItem.html

**Comment by derjust** [comment]
The `deleteById` is fixed in `v5.0` and `v4.5.5`.
Other half still needs investigation

**Comment by derjust** [comment]
Fixed with #143
