### ISSUE TITLE
findByKeyAndOtherKey throws an exception instead returns null / Optional.empty().

### ISSUE THREAD

**Issue by Dmitry-Erokhin** [derjust/spring-data-dynamodb#47]
`findOne(hashIdFieldValue)` returns null if no entries matched

at same time custom `findByKeyAndOtherKey` throws `EmptyResultDataAccessException` when there is no matches.

Please see [Spring data documentation](http://docs.spring.io/spring-data/commons/docs/current/reference/html/#repository-query-return-types)

**Comment by derjust** [comment]
related to #51?

**Comment by derjust** [comment]
Will be available in `5.0.3` 
Already provided via `5.0.3-SNAPSHOT`
