### ISSUE TITLE
Date marshaller UTC time zone discrepancy

### ISSUE THREAD

**Issue by fpoolev** [derjust/spring-data-dynamodb#49]
I recently ran into a problem in which a DynamoDB Date field was marshalling differently depending on the time zone of the machine it was being run on. We are attempting to read a preexisting UTC epoch time from a file and marshall the Date object created from this time into a UTC timestamp on a remote server. After some experimentation, we realized that we could fix the problem by simply changing the remote server time zone to our local time zone however I would like the ability to leave the remote server set using the UTC time zone.

I did some initial investigation and I am wondering if there may be problem with the Date marshaller if the Date that is being marshalled is already measured in reference to the UTC time zone. I noticed that the SimpleDateFormat always sets the time zone to UTC.

https://docs.oracle.com/javase/8/docs/api/java/text/DateFormat.html#setTimeZone-java.util.TimeZone-

The classes in question so far are:
DateDynamoDBMarshaller.java
Date2IsoDynamoDBMarshaller.java
Date2EpocheDynamoDBMarshaller.java

Does anyone have any ideas what is going on? I would greatly appreciate any and all help.

**Comment by derjust** [comment]
Yes the idea is always to store timezone information with the date representation in DynamoDB.

To investigate further, which Marshaller did you use to store the data?
Do the saved data in DyanmoDB match with what was read form the file?

**Comment by fpoolev** [comment]
I didn't specify a marshaller explicitly (either Date2IsoDynamoDBMarshaller or Date2EpocheDynamoDBMarshaller). I was under the impression that the marshaller was inferred by this project from the annotation alone. Do I need to annotate the field like this?
@DynamoDBMarshalling(marshallerClass = Date2IsoDynamoDBMarshaller.class)
or
@DynamoDBMarshalling(marshallerClass = Date2EpocheDynamoDBMarshaller.class)

Anyways I used the following Date constructor (using UTC ms precision epoch):
https://docs.oracle.com/javase/8/docs/api/java/util/Date.html#Date-long-

And then I have the Date as the range key of a composite DynamoDB key. The following getter is exposed in the table item class:
@DynamoDBRangeKey(attributeName = "timestamp")
    public Date getTimestamp() {
        ...
    }

And then the following attribute is specified in the composite id class:
@DynamoDBRangeKey
    private Date timestamp;

I will need to reproduce the problem to get the exact output again but my recollection is that the Date saved in DynamoDB was correct except the hours were off by the difference between UTC/GMT and my local time zone.

**Comment by derjust** [comment]
It might be related to the fact that it is a range key.
Have to dig into that and reproduce. Thanks so far for the feedback

**Comment by fpoolev** [comment]
I was able to do some more digging on this today. Under the hood, when the SimpleDateFormat time zone is set to UTC, the underlying Calendar instance has all of it's fields converted relative to the new time zone set.

`public class Date2IsoDynamoDBMarshaller extends DateDynamoDBMarshaller {

	private static final String PATTERN = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'";
	private static final TimeZone UTC = TimeZone.getTimeZone("UTC");

	@Override
	public DateFormat getDateFormat() {
		SimpleDateFormat df = new SimpleDateFormat(PATTERN);
		df.setTimeZone(UTC);
		return df;
	}
}`

The source code for Calendar.setTimeZone(TimeZone value) has the following description:
        /* Recompute the fields from the time using the new zone.  This also
         * works if isTimeSet is false (after a call to set()).  In that case
         * the time will be computed from the fields using the new zone, then
         * the fields will get recomputed from that.  Consider the sequence of
         * calls: cal.setTimeZone(EST); cal.set(HOUR, 1); cal.setTimeZone(PST).
         * Is cal set to 1 o'clock EST or 1 o'clock PST?  Answer: PST.  More
         * generally, a call to setTimeZone() affects calls to set() BEFORE AND
         * AFTER it up to the next call to complete().
         */

So it looks like Calendar.setTimeZone is writing the hour offset using the time zone in the underlying Calendar that SimpleDateFormat uses which for whatever reason defaults to the local time zone.

That said, I am looking to be able to marshall a Date into a UTC ISO String using the time zone as a parameter in a way that the inner Calendar of SimpleDateFormat can be set without causing a time offset relative to the system time zone. Basically I need to handle different time zones completely independently of the default system time zone.

**Comment by fpoolev** [comment]
After analyzing the initial problem that prompted me to post this issue more closely, I have confirmed that the time zone discrepancy occurred prior to marshalling in our own system. After testing both the date and instant marshallers, I'm convinced the problem is unrelated to this project. I apologize for the distraction :)

**Comment by derjust** [comment]
Thanks for your feedback.
Given that the SDK nowadays comes with a decent converter I might drop them with the next major release of `spring-data-dynamodb`
