### ISSUE TITLE
Doesn't work with Spring Data Commons 1.12.2.RELEASE

### ISSUE THREAD

**Issue by Raniz85** [derjust/spring-data-dynamodb#50]
This version is used with latest Spring Boot.

Signature of `QueryLookupStrategy.resolveQuery` has changed from
```RepositoryQuery resolveQuery(Method method, RepositoryMetadata metadata, NamedQueries namedQueries);```
to 
```RepositoryQuery resolveQuery(Method method, RepositoryMetadata metadata, ProjectionFactory factory, NamedQueries namedQueries);```

This causes a `java.lang.AbstractMethodError` on startup.

**Comment by derjust** [comment]
Please checkout version `4.4.0` that should be available in a few hours in Maven Central
