### ISSUE TITLE
spring-data-dynamodb 4.4.0 unavailable in maven/sonatype repositories

### ISSUE THREAD

**Issue by anandchida** [derjust/spring-data-dynamodb#53]

**Comment by derjust** [comment]
You are right. Thanks for reporting.
Will investigate

**Comment by varunmehta** [comment]
I'm stuck on this too;
 #50 is closed, but 4.4.0 is not available. Please let us know once this is ready.

**Comment by derjust** [comment]
Tried to do a new release. It went through Sonatype's Nexus. Let's hope it appears in Central soon

**Comment by derjust** [comment]
`4.4.1` (which is the same as `4.4.0`) is available in Maven Central:
https://repo1.maven.org/maven2/com/github/derjust/spring-data-dynamodb/4.4.1/
It might not appear in Maven Central searches yet but Maven & Co should be already be able to pull it

**Comment by anandchida** [comment]
Thanks! All worked out well! Appreciate all your help.

**Comment by varunmehta** [comment]
Was able to use `4.4.1`. The build worked! Thanks for the quick turn around
