### ISSUE TITLE
java.lang.ClassNotFoundException: com.amazonaws.ClientConfigurationFactory

### ISSUE THREAD

**Issue by tomhughesnice** [derjust/spring-data-dynamodb#54]
Hi,

I am trying to setup this library in my existing Spring boot project but I getting the following error.

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.amazonaws.services.dynamodbv2.AmazonDynamoDB]: Factory method 'amazonDynamoDB' threw exception; nested exception is java.lang.NoClassDefFoundError: com/amazonaws/ClientConfigurationFactory
```

I am using Spring Boot 1.4 and I just added the following to my pom.xml

```xml
<dependency>
            <groupId>com.github.derjust</groupId>
            <artifactId>spring-data-dynamodb</artifactId>
            <version>4.4.1</version>
        </dependency>
```

Should I add the AWS SDK separately to my pom.xml too? 

Do you have an example project setup that I can facilitate the basic functionality of the homepage README? Messing around with alot of transitive dependancies can be abit of a minefield.

**Comment by derjust** [comment]
can you please post the output of `mvn dependency:tree`?
Sounds to me that you have multiple (transitive) dependencies of AWS SDK on your classpath.

**Comment by tomhughesnice** [comment]
You are correct. I already have spring-cloud-aws-context on the classpath.

I have just excluded the bundled dynamodb sdk
```
<dependency>
    <groupId>com.github.derjust</groupId>
    <artifactId>spring-data-dynamodb</artifactId>
    <version>4.4.1</version>
    <exclusions>
        <exclusion>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-dynamodb</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-dynamodb</artifactId>
    <version>${aws-java-sdk-dynamodb.version}</version>
</dependency>
```

**Comment by derjust** [comment]
Out of curiosity:

* Can you tell from which dependency this was added?
* Can you tell with version the other library uses? so between which AWS SDK versions was the clash?
