### ISSUE TITLE
Example for 'Altering table name during runtime' seems broken

### ISSUE THREAD

**Issue by mikkiweesenaar** [derjust/spring-data-dynamodb#56]
Hello guys,

Im fairly new to the whole Spring-thing, however I have great colleagues around me who are more experienced with Spring.
Now I got into a problem where I needed to prefix the Dynamo tables, so that we can make distinction between the various test environments, live, etc.
A colleague pointed me towards [your wiki (Alter-table-name-during-runtime)](https://github.com/derjust/spring-data-dynamodb/wiki/Alter-table-name-during-runtime) where I found an example to get it to work. However, it seems that (atleast my Spring Tool Suite) doesn't like it.

On [this pastebin](http://pastebin.com/sDeQzk3E) you can find the code I copied and the error that STS throws is at line 20 and sounds as following:
`The method setTableNameResolver(DynamoDBMapperConfig.TableNameResolver) in the type DynamoDBMapperConfig.Builder is not applicable for the arguments (DynamoDBMapperConfig.TableNameOverride)`

Is there something I don't fully understand yet, which introduces this error or has something changed in related parts of the code?

Cheers and thanks in advance!

**Comment by derjust** [comment]
The wiki page had a type: The method name is called `setTableNameOverride`.
I updated the wiki accordingly. 

Can you confirm that it works as desired with the different method name? (I do not have a STS at hand right now)
Thanks

**Comment by mikkiweesenaar** [comment]
The code doesn't raise any errors anymore- thanks :-)
However, I do see that the table name is not being prefixed with (in my case) test.

When stepping into `EventIndexRepository.count()`, the config shows it does not have a `TableNameOverride` - and the request itself shows that it points to the unprefixed table.
Any tips for debugging this one?

![image](https://cloud.githubusercontent.com/assets/17587486/18713940/5ec9e084-8014-11e6-92b1-94d33535dedb.png)

**Comment by derjust** [comment]
(Leave the discussion here)

Double check that your bean name is right:

```dynamoDBMapperConfigRef = "dynamoDBMapperConfig"```

Is very picky and if I remember correctly there is even not a warning logged if the bean is not found - it just silently ignores it.

And are you sure you use that `DynamoDBConfig` or may you accidentally creating/using a second one?

**Comment by mikkiweesenaar** [comment]
We have exactly that line.
Currently we're looking into the code again. We could verify that the demo is not using Spring Boot, where we do. I'll keep you posted. :-)

**Comment by mikkiweesenaar** [comment]
We might have found the problem... -facepalms-
A colleague, at some point, reminded himself that he manually added bean configurations (for...DynamoDB) to the `spring-context.xml`.

So I will close the ticket.
Atleast I was somewhat useful, for raising the problem with regards to the documentation 😄 👍
