### ISSUE TITLE
Need a way to find all with limit and exclusive start key.

### ISSUE THREAD

**Issue by kushal154** [derjust/spring-data-dynamodb#61]
I am able to use findAll(Pageable p) to put limit on the number of rows returned. But I also want to specify exclusive start key. How do I do it?

P.S. I tried to define my own repository implementation extending DynamoDBPagingAndSortingRepository, but I am not able to make the Spring Data infrastructure aware of the customized repository base class.

**Comment by kushal154** [comment]
Any inputs on this?

**Comment by kushal154** [comment]
I managed to find a way out by extending SimpleDynamoDBPagingAndSortingRepository and then creating custom factory and custom factory bean.

**Comment by jainbhargav** [comment]
Hello @kushal154 , Can you please shed some light on how did you use exclusive start key with findAll method? I guess there isn't any inbuilt support in Spring-data-dynamodb for the same. Any help will be appreciated!
