### ISSUE TITLE
Please support @DynamoDBTypeConverted instead of/in addition to @DynamoDBMarshalling for query methods

### ISSUE THREAD

**Issue by spatula75** [derjust/spring-data-dynamodb#62]
Today, query methods only seem to understand @DynamoDBMarshalling, which is a deprecated annotation in DynamoDB (and kind of obnoxious because it only supports going to/from Strings, which makes it lousy for dates).

It would be awesome if DynamoDBTypeConverted fields were supported by AbstractDynamoDBQueryCriteria so that fields annotated in this way would work with query methods.

**Comment by alex-arana** [comment]
+1

**Comment by mattcorey** [comment]
+1

**Comment by alexarana** [comment]
NOTES
=====

I have added https://github.com/derjust/spring-data-dynamodb/pull/79 to deal with this very issue.

This change introduces support for DynamoDBMapper v2 conversion schemas with support for all relevant annotations including:

- DynamoDBTypeConverted
- DynamoDBTypeConvertedEnum
- DynamoDBTypeConvertedTimestamp
- DynamoDBTyped

Also, any custom meta-annotations including one or more of the above would be equally supported using the new code.

I've left a few TODOs in the code where feedback is particularly sought.

**Comment by fpoolev** [comment]
+1

**Comment by spatula75** [comment]
It would also be nice to support @DynamoDBTypeConverted{Enum|EpochDate|JsonTimestamp}

**Comment by derjust** [comment]
Thanks for the PR. I merged it and therefore close this issue

**Comment by pyteld** [comment]
@derjust could you release new version from branch 4.6.x with this fix?

**Comment by alex-arana** [comment]
I'm currently away until early Jan but is doable..

Alex

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by ronniehicks** [comment]
I'm not sure if I'm doing something wrong here, but I can't seem to get this to work. I have an entity object with a `@DynamoDBTypeConvertedEnum` annotation directly on the field and when trying to write a `findByStatus` method I'm getting the following error. Any thoughts? 

> Cannot create condition for type:class x property conditions must be String,Number or Boolean, or have a DynamoDBMarshaller configured

**Comment by ryankazokas** [comment]
@ronniehicks are you using the correct version? It looks like the PR was merged in to v5.0.1. I have the same issue with version < 5 and had to use the @DynamoDBMarshalling annotation.

**Comment by ronniehicks** [comment]
> It looks like the PR was merged in to v5.0.1

I was not aware of that. The project I'm on is currently using Spring Boot 1.5.7, which relies on Spring 4, and we're not super comfortable upgrading to the version that needs Spring 5 quite yet. Think there's any chance that this could get pulled into the v4 release?

**Comment by derjust** [comment]
I will have a look what the impact would be

**Comment by derjust** [comment]
@ronniehicks want to give `4.5.4` a shot? 😀
It should be available in Central within the next minutes. If you still encounter any other issues please open a new issue (and refer this one).
