### ISSUE TITLE
Batch save doesn't return list of failed operations

### ISSUE THREAD

**Issue by jasiustasiu** [derjust/spring-data-dynamodb#68]
CrudRepository has a method 
`<S extends T> Iterable<S> save(Iterable<S> entities)`
 which now returns all entities given as a parameter no matter if operation was successful or not. In fact it runs DynamoDBMapper method 
`public List<FailedBatch> batchWrite(Iterable<? extends Object> objectsToWrite, Iterable<? extends Object> objectsToDelete, DynamoDBMapperConfig config)`
Result of a method is ignored and we lose information what went wrong.
Can you please fix it?

**Comment by derjust** [comment]
Part of `5.0.1` now
