### ISSUE TITLE
Application failed to start after updating to 4.5.0

### ISSUE THREAD

**Issue by eatyours0up** [derjust/spring-data-dynamodb#75]
I could use some help, I recently updated from 4.3.1 to 4.5.0 and I'm running into the issue below. Has anyone ran into this problem before? I tried using the DynamoDBCrudRepository instead of the CrudRepository but that didnt seem to matter.

`***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in org.socialsignin.spring.data.dynamodb.repository.support.DynamoDBRepositoryFactoryBean required a bean of type 'java.lang.Class' that could not be found.

Action:

Consider defining a bean of type 'java.lang.Class' in your configuration.`

**Comment by derjust** [comment]
Can you please check your classpath? What is your version of spring-data and/or spring boot?

**Comment by eatyours0up** [comment]
Thanks for the quick response! The error is definitely related to some dependency issues I'm having, although I haven't been able to pin point it yet. I was attempting to use a spring cloud config server, which is what I believe is causing the issue. This is the dependency that is breaking everything for me.

`			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Brixton.RELEASE</version>
				<type>pom</type>
				<scope>test</scope>
			</dependency>
`

**Comment by eatyours0up** [comment]
Bingo! I'm assuming that the Brixton.RELEASE version of spring cloud is not supported. Everything is working fine when using the Camden.RELEASE version.

```xml
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-dependencies</artifactId>
	<version>Camden.RELEASE</version>
	<type>pom</type>
	<scope>import</scope>
</dependency>
