### ISSUE TITLE
Help With Spring-Boot integration

### ISSUE THREAD

**Issue by Burca-Vlad** [derjust/spring-data-dynamodb#80]
Hello,

I tried to add this library to a spring boot implementation that I have in combination with Data Rest. I could get the repository to work but not in combination with Data Rest.  I have added a sample project here https://github.com/Burca-Vlad/example-dynamodb with how I tried. Can I please get some help with this issue?

**Comment by adulescentulus** [comment]
same with me. didn't get this to work. stuck at the same point. The entity is not registered

**Comment by derjust** [comment]
Yes it is currently not supported and already reported here: #15
