### ISSUE TITLE
Issue with findByAttribue(List<String>  names)

### ISSUE THREAD

**Issue by ravichauhan03** [derjust/spring-data-dynamodb#84]
We have a use case in which we have below object and the corresponding mappings:
```
@DynamoDBTable(tableName="user_profile")
public class UserProfile implements Serializable{
	@Id
	@DynamoDBHashKey(attributeName="id") 
	private String id;
        @DynamoDBAttribute(attributeName="mobile") 
	private String mobileNumber;	
        @DynamoDBAttribute(attributeName="email") 
	private String email;
        @DynamoDBAttribute(attributeName="dob") 
	private String dateOfBirth;
        @DynamoDBAttribute(attributeName="fname")
	private String firstName;
        @DynamoDBAttribute(attributeName="lname")
	private String lastName;

//getter & setters
}
```
Also, we have a repository in which we are extending CrudRepository and when we are doing 
`findByFirstName(String fname)` - it works fine

but, how to retrieve the `List<UserProfile>` where we can do something like `findByFirstName(List<String> fnameList)` ???

Can someone help in here ??

**Comment by ravichauhan03** [comment]
Can someone please look into it ??

**Comment by foxware00** [comment]
`List<UserProfile> findByFirstName(String firstName) `

**Comment by ravichauhan03** [comment]
No, this thing I already know. In case of List of firstNames how do I search  ??

**Comment by foxware00** [comment]
`List<UserProfile> findByFirstNameIn(List<String> firstNames);`

**Comment by derjust** [comment]
This somewhat tapped into spring-data magic itself. 
Did @foxware00 proposal work (It should according to the reference documentation with `in` or `isIn`https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repository-query-keywords)

**Comment by derjust** [comment]
Confirmed via Testcase in #143
