### ISSUE TITLE
Will dax supported by spring data dynamodb 

### ISSUE THREAD

**Issue by gauravbrills** [derjust/spring-data-dynamodb#90]
Can we use dax with spring data dynamodb if we use the dax client for the dynamodbmapper as below .
```  public DynamoDBMapper dynamoDBMapper(final ClientConfiguration clientConfiguration)
      {
         
         ClientConfig daxConfig = new ClientConfig().withRegion(Regions.US_EAST_1.getCurrentRegion())
               .withEndpoints("testcache.amazonaws.com:8111");
         AmazonDaxClient client = new ClusterDaxClient(daxConfig);
         return new DynamoDBMapper(client);
      }
```
This is the scenario when we are setting up dax as a write through cache behind Amazon DynamoDB

**Comment by chenrui333** [comment]
+1

**Comment by derjust** [comment]
Any chance to get more infos on dax?

**Comment by derjust** [comment]
`spring-data-dynamodb` does _not_ have any state information - in fact most of the classes are Spring Bean singletons that never should have any (shared) state.

Therefore it is fine to use DAX from a `spring-data-dynamodb` perspective - inject the `ClientConfig` as per the documentation.
Will update the documentation.

**Comment by derjust** [comment]
Documentation added to the [wiki](https://github.com/derjust/spring-data-dynamodb/wiki/Amazon-DynamoDB-Accelerator-(DAX)).
