### ISSUE TITLE
Allow custom DynamoDB mapper with AttributeTransformer

### ISSUE THREAD

**Issue by micw** [derjust/spring-data-dynamodb#91]
In my use-case I need to encrypt all data in DynamoDB. Fortunately there's a ready-to-use tool from AWS that implements encryption using an AttributeTransformer.
A DynamoDBMapper can be constructed with an AttributeTransformer that is used then. Since spring-data-dynamodb can use a user-provided DynamoDBTemplate it'spossible to inject it at this point.
The problem is that DynamoDBTemplate has no way to set DynamoDBTemplate programmatically nor has it a way to pass an AttributeTransformer. I "fix" this by using reflection but that's not how it should work.

**Comment by derjust** [comment]
Closed as merged

**Comment by ryonday** [comment]
Is there a chance we can get this ported to the 4.5.x line and a 4.5.1 released? We are on Spring Boot 1.5.9, and therefore have to use 4.5.0 at the moment. I am in need of using `AttributeTransformer` and would rather not have to resort to reflection.

Thank you!

**Comment by gauravbrills** [comment]
@derjust  Also is this available in the 5.0.0 release I also have a similar use case . Also similar to dynamoDBMapperConfigRef can we have an attribute wherein we can pass the DynamodbMapper as well ?

**Comment by derjust** [comment]
@gauravbrills yes this is part of the `5.0.x` line

**Comment by gauravbrills** [comment]
Yes found it thanks

**Comment by derjust** [comment]
[v.4.5.1](https://github.com/derjust/spring-data-dynamodb/releases/tag/v4.5.1) is right now publishing to Maven Central

**Comment by gauravbrills** [comment]
@derjust  when running the same get the below error I guess cause of the assert for the dynamoDbMapper , do we need the assert if we supplying the dynamodb mapper with the new constructor provided ?

```
Caused by: java.lang.AssertionError: null
	at org.socialsignin.spring.data.dynamodb.core.DynamoDBTemplate.<init>(DynamoDBTemplate.java:60)
	at org.socialsignin.spring.data.dynamodb.core.DynamoDBTemplate.<init>(DynamoDBTemplate.java:46)
	at com.wellmanage.wfg.fdps.DynamoDBTestConfig.dynamoDbOperations(DynamoDBTestConfig.java:83)
```

**Comment by gauravbrills** [comment]
For now created a custom Dynamodbtemplate to solve this and passing it as a dynamodboperationRef .. had to make the following changes to skip the assert check 
`DynamoDBTemplate(AmazonDynamoDB amazonDynamoDB, DynamoDBMapperConfig dynamoDBMapperConfig,
         DynamoDBMapper dynamoDBMapper)
   {
      this.amazonDynamoDB = amazonDynamoDB;
      if (dynamoDBMapper == null && dynamoDBMapperConfig == null)
      {
         this.dynamoDBMapperConfig = DynamoDBMapperConfig.DEFAULT;
         this.dynamoDBMapper = new DynamoDBMapper(amazonDynamoDB);
        // Mapper must be null as it could not have been constructed without a Config
            assert dynamoDBMapper == null;
      }
      else
      {
         this.dynamoDBMapperConfig = dynamoDBMapperConfig;
         if (dynamoDBMapper == null)
         {
            this.dynamoDBMapper = new DynamoDBMapper(amazonDynamoDB, dynamoDBMapperConfig);
         }
         else
         {
            this.dynamoDBMapper = dynamoDBMapper;
         }
      }
   }`

do review this , I guess it needs to be changed or will do a PR

**Comment by derjust** [comment]
#105 cherry-picked & added unit tests (and fixed a typo) 👍 
* merged into `master` as #106
* merged into `v4.5.x` as #107  - released `4.5.2` to Maven Central

Thanks & happy holidays 🎄 @gauravbrills

**Comment by gauravbrills** [comment]
Great..Happy holidays 🎄 to you too @derjust 😊

**Comment by kpcsuh** [comment]
In my case I need both Dynamo Table prefix like (DEV_, QA_, etc) and encrypt all data in DynamoDB.
Right now, DynamoDBTemplate constructor takes either DynamoDBMapperConfig or DynamoDBMapper but not both. Any solution for my problem?

I think below constructor should be public as well? I may wrong.

DynamoDBTemplate(AmazonDynamoDB amazonDynamoDB, DynamoDBMapperConfig dynamoDBMapperConfig, DynamoDBMapper dynamoDBMapper)
