### ISSUE TITLE
Is this repo still being maintained

### ISSUE THREAD

**Issue by ryankazokas** [derjust/spring-data-dynamodb#95]
I have a couple issues and see a couple that I want to fix. It seems like comments have been going unanswered on issues and there doesn't seem to be any active merge requests be completed. Any info is much appreciated.

**Comment by derjust** [comment]
I try - it's quite hard given my current position. 
Any help is appreciated and I try to merge PRs that I can review in small breaks. 
Try to become more active again - but won't happen before December sadly

**Comment by derjust** [comment]
As #98 is solved marking this as 'solved' 😬
