### ISSUE TITLE
Spring 5 upgrade?

### ISSUE THREAD

**Issue by cthiebault** [derjust/spring-data-dynamodb#98]
Is there a plan to upgrade to Spring 5 soon as it is now released ?
Spring Data release train Kay is also released...

**Comment by derjust** [comment]
Def. on the more important things to do, yes

**Comment by derjust** [comment]
Happy for feedback on https://github.com/derjust/spring-data-dynamodb/pull/100 - Try to provide a snapshot build but building locally should be easy as a `mvn install` (version `5.0.0-SNAPSHOT`)

**Comment by derjust** [comment]
Available as `5.0.0` in Maven Central
